import { NextRequest, NextResponse } from "next/server";

export const dynamic = "force-dynamic";

const BOILERPLATE: Record<string, { content: string; language: string }> = {
  "package.json": {
    language: "json",
    content: JSON.stringify({
      name: "njirlah-project",
      version: "0.1.0",
      private: true,
      scripts: { dev: "next dev", build: "next build", start: "next start" },
      dependencies: { next: "14.0.4", react: "^18", "react-dom": "^18", "tailwindcss": "^3", "autoprefixer": "^10", "postcss": "^8" },
      devDependencies: { typescript: "^5", "@types/react": "^18", "@types/node": "^20" },
    }, null, 2),
  },
  "app/layout.tsx": {
    language: "tsx",
    content: `import type { Metadata } from "next";
import "./globals.css";
export const metadata: Metadata = { title: "NJIRLAH Project", description: "Generated by NJIRLAH AI" };
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (<html lang="id"><body>{children}</body></html>);
}`,
  },
  "app/globals.css": {
    language: "css",
    content: `@tailwind base;\n@tailwind components;\n@tailwind utilities;\n\n* { box-sizing: border-box; }\nhtml, body { height: 100%; margin: 0; }`,
  },
  "tailwind.config.ts": {
    language: "typescript",
    content: `import type { Config } from "tailwindcss";
const config: Config = {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: { extend: {} },
  plugins: [],
};
export default config;`,
  },
  "tsconfig.json": {
    language: "json",
    content: JSON.stringify({ compilerOptions: { target: "es5", lib: ["dom", "dom.iterable", "esnext"], allowJs: true, skipLibCheck: true, strict: true, noEmit: true, esModuleInterop: true, module: "esnext", moduleResolution: "bundler", resolveJsonModule: true, isolatedModules: true, jsx: "preserve", incremental: true, plugins: [{ name: "next" }], paths: { "@/*": ["./*"] } }, include: ["next-env.d.ts", "**/*.ts", "**/*.tsx"], exclude: ["node_modules"] }, null, 2),
  },
  "next.config.js": {
    language: "javascript",
    content: `/** @type {import('next').NextConfig} */\nconst nextConfig = { images: { unoptimized: true } };\nmodule.exports = nextConfig;`,
  },
  ".gitignore": {
    language: "text",
    content: "node_modules\n.next\n.env\n.env.local\ndist\nbuild\n",
  },
};

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { path: filePath } = body;
    if (!filePath) return NextResponse.json({ error: "Missing path" }, { status: 400 });
    const found = BOILERPLATE[filePath];
    if (!found) return NextResponse.json({ error: `No builtin for ${filePath}`, available: Object.keys(BOILERPLATE) }, { status: 404 });
    return NextResponse.json({ path: filePath, content: found.content, language: found.language });
  } catch (e) {
    return NextResponse.json({ error: (e as Error).message }, { status: 500 });
  }
}
