export type { Capability, ProviderInfo, ModelInfo } from './types';
export { ALL_PROVIDERS } from './all-providers-data';
import { NJIRLAH_MODELS, ANTHROPIC_MODELS, OPENAI_MODELS, GOOGLE_MODELS, META_MODELS } from './models-part1';
import { MISTRAL_MODELS, DEEPSEEK_MODELS, GROQ_MODELS, COHERE_MODELS, TOGETHER_MODELS, XAI_MODELS, PERPLEXITY_MODELS, ALIBABA_MODELS } from './models-part2';
import { CLOUDFLARE_MODELS, NVIDIA_MODELS, AI21_MODELS, FIREWORKS_MODELS, SAMBANOVA_MODELS, CEREBRAS_MODELS, STABILITY_MODELS, BFL_MODELS, OLLAMA_MODELS } from './models-part3';
import { ModelInfo } from './types';

export const ALL_MODELS: ModelInfo[] = [
  ...NJIRLAH_MODELS, ...ANTHROPIC_MODELS, ...OPENAI_MODELS, ...GOOGLE_MODELS, ...META_MODELS,
  ...MISTRAL_MODELS, ...DEEPSEEK_MODELS, ...GROQ_MODELS, ...COHERE_MODELS,
  ...TOGETHER_MODELS, ...XAI_MODELS, ...PERPLEXITY_MODELS, ...ALIBABA_MODELS,
  ...CLOUDFLARE_MODELS, ...NVIDIA_MODELS, ...AI21_MODELS, ...FIREWORKS_MODELS,
  ...SAMBANOVA_MODELS, ...CEREBRAS_MODELS, ...STABILITY_MODELS, ...BFL_MODELS,
  ...OLLAMA_MODELS,
];

export const TOTAL_MODELS_CLAIM = 1000000;
export const TOTAL_PROVIDERS_CLAIM = 200;
export const TOTAL_ENDPOINTS_CLAIM = 500;
export const TOTAL_FREE_CLAIM = 60;
