import { ModelInfo } from './types';

export const NJIRLAH_MODELS: ModelInfo[] = [
  { id: 'NJIRLAH-1-SS', name: 'NJIRLAH-1-SS', providerId: 'njirlah', context: 32000, inputPrice: 0, outputPrice: 0, capabilities: ['text','code','reasoning'], endpoint: '/api/njirlah/chat', authExample: 'None (Built-in)', isOpenSource: false, license: 'Proprietary', speed: 'fast', isNew: true },
];

export const ANTHROPIC_MODELS: ModelInfo[] = [
  { id: 'claude-opus-4-5', name: 'Claude Opus 4.5', providerId: 'anthropic', context: 200000, inputPrice: 15, outputPrice: 75, capabilities: ['text','vision','code','reasoning'], endpoint: 'https://api.anthropic.com/v1/messages', authExample: 'x-api-key: sk-ant-xxxxx', isOpenSource: false, license: 'Commercial', speed: 'slow' },
  { id: 'claude-sonnet-4-5', name: 'Claude Sonnet 4.5', providerId: 'anthropic', context: 200000, inputPrice: 3, outputPrice: 15, capabilities: ['text','vision','code'], endpoint: 'https://api.anthropic.com/v1/messages', authExample: 'x-api-key: sk-ant-xxxxx', isOpenSource: false, license: 'Commercial', speed: 'medium' },
  { id: 'claude-haiku-4-5', name: 'Claude Haiku 4.5', providerId: 'anthropic', context: 200000, inputPrice: 0.25, outputPrice: 1.25, capabilities: ['text','vision','streaming'], endpoint: 'https://api.anthropic.com/v1/messages', authExample: 'x-api-key: sk-ant-xxxxx', isOpenSource: false, license: 'Commercial', speed: 'fast' },
  { id: 'claude-3-opus-20240229', name: 'Claude 3 Opus', providerId: 'anthropic', context: 200000, inputPrice: 15, outputPrice: 75, capabilities: ['text','vision'], endpoint: 'https://api.anthropic.com/v1/messages', authExample: 'x-api-key: sk-ant-xxxxx', isOpenSource: false, license: 'Commercial', speed: 'slow' },
  { id: 'claude-3-5-sonnet-20241022', name: 'Claude 3.5 Sonnet', providerId: 'anthropic', context: 200000, inputPrice: 3, outputPrice: 15, capabilities: ['text','vision','code'], endpoint: 'https://api.anthropic.com/v1/messages', authExample: 'x-api-key: sk-ant-xxxxx', isOpenSource: false, license: 'Commercial', speed: 'medium' },
  { id: 'claude-3-5-haiku-20241022', name: 'Claude 3.5 Haiku', providerId: 'anthropic', context: 200000, inputPrice: 0.80, outputPrice: 4, capabilities: ['text','vision'], endpoint: 'https://api.anthropic.com/v1/messages', authExample: 'x-api-key: sk-ant-xxxxx', isOpenSource: false, license: 'Commercial', speed: 'fast' },
  { id: 'claude-3-haiku-20240307', name: 'Claude 3 Haiku', providerId: 'anthropic', context: 200000, inputPrice: 0.25, outputPrice: 1.25, capabilities: ['text','vision'], endpoint: 'https://api.anthropic.com/v1/messages', authExample: 'x-api-key: sk-ant-xxxxx', isOpenSource: false, license: 'Commercial', speed: 'fast' },
  { id: 'claude-2.1', name: 'Claude 2.1', providerId: 'anthropic', context: 200000, inputPrice: 8, outputPrice: 24, capabilities: ['text'], endpoint: 'https://api.anthropic.com/v1/messages', authExample: 'x-api-key: sk-ant-xxxxx', isOpenSource: false, license: 'Commercial', speed: 'medium' },
];

export const OPENAI_MODELS: ModelInfo[] = [
  { id: 'gpt-4o', name: 'GPT-4o', providerId: 'openai', context: 128000, inputPrice: 2.50, outputPrice: 10, capabilities: ['text','vision','audio','function-calling','streaming'], endpoint: 'https://api.openai.com/v1/chat/completions', authExample: 'Authorization: Bearer sk-xxxxx', isOpenSource: false, license: 'Commercial', speed: 'fast' },
  { id: 'gpt-4o-mini', name: 'GPT-4o Mini', providerId: 'openai', context: 128000, inputPrice: 0.15, outputPrice: 0.60, capabilities: ['text','vision','function-calling'], endpoint: 'https://api.openai.com/v1/chat/completions', authExample: 'Authorization: Bearer sk-xxxxx', isOpenSource: false, license: 'Commercial', speed: 'fast' },
  { id: 'gpt-4-turbo', name: 'GPT-4 Turbo', providerId: 'openai', context: 128000, inputPrice: 10, outputPrice: 30, capabilities: ['text','vision'], endpoint: 'https://api.openai.com/v1/chat/completions', authExample: 'Authorization: Bearer sk-xxxxx', isOpenSource: false, license: 'Commercial', speed: 'medium' },
  { id: 'o1', name: 'o1', providerId: 'openai', context: 200000, inputPrice: 15, outputPrice: 60, capabilities: ['text','reasoning'], endpoint: 'https://api.openai.com/v1/chat/completions', authExample: 'Authorization: Bearer sk-xxxxx', isOpenSource: false, license: 'Commercial', speed: 'slow', isNew: true },
  { id: 'o3', name: 'o3', providerId: 'openai', context: 200000, inputPrice: 10, outputPrice: 40, capabilities: ['text','reasoning'], endpoint: 'https://api.openai.com/v1/chat/completions', authExample: 'Authorization: Bearer sk-xxxxx', isOpenSource: false, license: 'Commercial', speed: 'slow', isNew: true },
  { id: 'o3-mini', name: 'o3 Mini', providerId: 'openai', context: 200000, inputPrice: 1.10, outputPrice: 4.40, capabilities: ['text','reasoning'], endpoint: 'https://api.openai.com/v1/chat/completions', authExample: 'Authorization: Bearer sk-xxxxx', isOpenSource: false, license: 'Commercial', speed: 'medium' },
  { id: 'o4-mini', name: 'o4 Mini', providerId: 'openai', context: 200000, inputPrice: 1.10, outputPrice: 4.40, capabilities: ['text','vision','reasoning'], endpoint: 'https://api.openai.com/v1/chat/completions', authExample: 'Authorization: Bearer sk-xxxxx', isOpenSource: false, license: 'Commercial', speed: 'medium', isNew: true },
  { id: 'gpt-3.5-turbo', name: 'GPT-3.5 Turbo', providerId: 'openai', context: 16000, inputPrice: 0.50, outputPrice: 1.50, capabilities: ['text','function-calling'], endpoint: 'https://api.openai.com/v1/chat/completions', authExample: 'Authorization: Bearer sk-xxxxx', isOpenSource: false, license: 'Commercial', speed: 'fast' },
  { id: 'dall-e-3', name: 'DALL-E 3', providerId: 'openai', context: 0, inputPrice: 0.04, outputPrice: null, capabilities: ['image-gen'], endpoint: 'https://api.openai.com/v1/images/generations', authExample: 'Authorization: Bearer sk-xxxxx', isOpenSource: false, license: 'Commercial', speed: 'medium' },
  { id: 'whisper-1', name: 'Whisper', providerId: 'openai', context: 0, inputPrice: 0.006, outputPrice: null, capabilities: ['speech','audio'], endpoint: 'https://api.openai.com/v1/audio/transcriptions', authExample: 'Authorization: Bearer sk-xxxxx', isOpenSource: false, license: 'Commercial', speed: 'fast' },
  { id: 'text-embedding-3-large', name: 'Embedding 3 Large', providerId: 'openai', context: 8000, inputPrice: 0.13, outputPrice: null, capabilities: ['embedding'], endpoint: 'https://api.openai.com/v1/embeddings', authExample: 'Authorization: Bearer sk-xxxxx', isOpenSource: false, license: 'Commercial', speed: 'fast' },
];

export const GOOGLE_MODELS: ModelInfo[] = [
  { id: 'gemini-2.5-pro', name: 'Gemini 2.5 Pro', providerId: 'google', context: 1000000, inputPrice: 1.25, outputPrice: 10, capabilities: ['text','vision','audio','video','code'], endpoint: 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-pro:generateContent', authExample: '?key=YOUR_KEY', isOpenSource: false, license: 'Commercial', speed: 'medium', isNew: true },
  { id: 'gemini-2.5-flash', name: 'Gemini 2.5 Flash', providerId: 'google', context: 1000000, inputPrice: 0.075, outputPrice: 0.30, capabilities: ['text','vision','streaming'], endpoint: 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent', authExample: '?key=YOUR_KEY', isOpenSource: false, license: 'Commercial', speed: 'fast', isNew: true },
  { id: 'gemini-2.0-flash', name: 'Gemini 2.0 Flash', providerId: 'google', context: 1000000, inputPrice: 0.10, outputPrice: 0.40, capabilities: ['text','vision','streaming'], endpoint: 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent', authExample: '?key=YOUR_KEY', isOpenSource: false, license: 'Commercial', speed: 'fast' },
  { id: 'gemini-1.5-pro', name: 'Gemini 1.5 Pro', providerId: 'google', context: 2000000, inputPrice: 1.25, outputPrice: 5, capabilities: ['text','vision','audio'], endpoint: 'https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-pro:generateContent', authExample: '?key=YOUR_KEY', isOpenSource: false, license: 'Commercial', speed: 'medium' },
  { id: 'gemini-1.5-flash', name: 'Gemini 1.5 Flash', providerId: 'google', context: 1000000, inputPrice: 0.075, outputPrice: 0.30, capabilities: ['text','vision'], endpoint: 'https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent', authExample: '?key=YOUR_KEY', isOpenSource: false, license: 'Commercial', speed: 'fast' },
];

export const META_MODELS: ModelInfo[] = [
  { id: 'meta-llama/llama-4-maverick', name: 'Llama 4 Maverick', providerId: 'meta', context: 1000000, inputPrice: null, outputPrice: null, capabilities: ['text','code'], endpoint: 'via Groq/Together', authExample: 'Varies', isOpenSource: true, license: 'Meta Llama 4', parameters: '~400B MoE', speed: 'medium', isNew: true },
  { id: 'meta-llama/llama-4-scout', name: 'Llama 4 Scout', providerId: 'meta', context: 10000000, inputPrice: null, outputPrice: null, capabilities: ['text','code'], endpoint: 'via Groq/Together', authExample: 'Varies', isOpenSource: true, license: 'Meta Llama 4', parameters: '~109B MoE', speed: 'medium', isNew: true },
  { id: 'meta-llama/llama-3.3-70b-instruct', name: 'Llama 3.3 70B', providerId: 'meta', context: 128000, inputPrice: null, outputPrice: null, capabilities: ['text','code'], endpoint: 'via Groq/Together', authExample: 'Varies', isOpenSource: true, license: 'Meta Llama 3.3', parameters: '70B', speed: 'medium' },
  { id: 'meta-llama/llama-3.2-90b-vision', name: 'Llama 3.2 90B Vision', providerId: 'meta', context: 128000, inputPrice: null, outputPrice: null, capabilities: ['text','vision'], endpoint: 'via Groq/Together', authExample: 'Varies', isOpenSource: true, license: 'Meta Llama 3.2', parameters: '90B', speed: 'slow' },
  { id: 'meta-llama/llama-3.1-405b-instruct', name: 'Llama 3.1 405B', providerId: 'meta', context: 128000, inputPrice: null, outputPrice: null, capabilities: ['text','code'], endpoint: 'via Together/Fireworks', authExample: 'Varies', isOpenSource: true, license: 'Meta Llama 3.1', parameters: '405B', speed: 'slow' },
  { id: 'meta-llama/llama-3.1-8b-instruct', name: 'Llama 3.1 8B', providerId: 'meta', context: 128000, inputPrice: null, outputPrice: null, capabilities: ['text'], endpoint: 'via Groq/Ollama', authExample: 'Varies', isOpenSource: true, license: 'Meta Llama 3.1', parameters: '8B', speed: 'fast' },
];
